services:

  # Database, postgres for example
  postgres:
    image: postgres:alpine3.23
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=spellbook
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U postgres -d spellbook'" ]
      interval: 10s
      timeout: 1s
      retries: 5
    volumes:
    - postgres-data:/var/lib/postgresql/data

  migrations:
    image: ghcr.io/kukymbr/goose-docker:latest
    restart: no
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - GOOSE_DRIVER=postgres
      - GOOSE_DBSTRING=host=postgres port=5432 user=postgres password=postgres dbname=spellbook sslmode=disable
      - GOOSE_VERBOSE=true
      # Provide the `GOOSE_COMMAND` variable to change the goose command to execute:
      #- GOOSE_COMMAND=up-to
      #- GOOSE_COMMAND_ARG=20230607203836
      # Or a placeholders to set it dynamically from the environment:
      #- GOOSE_COMMAND=${GOOSE_COMMAND}
      #- GOOSE_COMMAND_ARG=${GOOSE_COMMAND_ARG}
    volumes:
      - ./sql/schema:/migrations
    
volumes:
  postgres-data:


